FROM rust:1.67


COPY . ./srv/git-repo-manager

WORKDIR ./srv/git-repo-manager

RUN apt-get update

RUN apt install -y protobuf-compiler

RUN cargo build --release

CMD ["./target/release/git-repo-manager"]