# Rust project
FROM rust:1-slim-bookworm

# prepare workspace
WORKDIR /app
COPY . .

# install necessary dependency
RUN apt-get update
RUN apt-get install -y protobuf-compiler

# build
RUN cargo build --release

# run the binary
CMD ["/app/target/release/git-repo-manager"]