#!/bin/bash

echo $IMAGE_NAME

if [ -z "$PWD" ]; then
  echo "PWD is not set"
  exit 1
fi

project_name=$(basename "$PWD")

branch="main"

ref="refs/heads/$BRANCH"

timestamp=$(date +%s.%N)

target="/tmp/deploy-dir-$project_name-$timestamp"

mkdir -p "$target"

git --work-tree="$target" --git-dir=. checkout -f "$branch"

# if there's a dockerfile, just use docker build
if [ -f "$target/Dockerfile" ]; then
  docker build -t "$IMAGE_NAME:latest" "$target"

  rm -rf "$target"

  if $? -ne 0; then
    echo "docker build failed"
    exit 1
  fi

  echo "docker build succeeded, you can now run : paastech deploy"
  exit 0
fi

pack build "$IMAGE_NAME:latest" --path "$target" --builder heroku/buildpacks:20

rm -rf "$target"

if $? -ne 0; then
  echo "pack build failed"
  exit 1
fi

echo "pack build succeeded, you can now run : paastech deploy"
