on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      image_name:
        required: true
        type: string
      context:
        required: true
        type: string

jobs:
  build-and-push-app:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ inputs.image_name }}
          tags: |
            type=sha
            latest
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: nologin
          password: ${{ secrets.CONTAINER_REGISTRY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
